# Default values for home-assistance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/home-assistant/home-assistant
  pullPolicy: IfNotPresent

loadBalancerIP: "10.0.3.5"

tz: "Europe/Madrid"

service:
  type: LoadBalancer
  port: 8123
  targetPort: 80

livenessProbe:
  tcpSocket:
    port: 8123
  initialDelaySeconds: 0
  failureThreshold: 3
  timeoutSeconds: 1
  periodSeconds: 10
readinessProbe:
  tcpSocket:
    port: 8123
  initialDelaySeconds: 0
  failureThreshold: 3
  timeoutSeconds: 1
  periodSeconds: 10
startupProbe:
  tcpSocket:
    port: 8123
  initialDelaySeconds: 0
  failureThreshold: 30
  timeoutSeconds: 1
  periodSeconds: 5

# Additional volumes on the output Deployment definition.
volumes:
  - name: ha-config-root
    persistentVolumeClaim:
      claimName: home-assistant-config-root

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: ha-config-root
    mountPath: /config
