apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-proxy.fullname" . }}
  annotations:
    metallb.universe.tf/allow-shared-ip: nginx-service
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: {{ include "http-proxy.name" . }}
