apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-svc-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-controller-svc
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  loadBalancerIP: 192.168.1.231
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: device-communication
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: web-admin
    - port: 6789
      targetPort: 6789
      protocol: TCP
      name: mobile-throughput-test
    - port: 8843
      targetPort: 8843
      protocol: TCP
      name: unifi-guest-portal-httsp-redirect-pool
    - port: 8888
      targetPort: 8880
      protocol: TCP
      name: unifi-guest-portal-http-redirect-pool
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-svc-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-controller-svc
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  loadBalancerIP: 192.168.1.231
  ports:
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: stun-port
    - port: 10001
      targetPort: 10001
      protocol: UDP
      name: ap-discovery
    - port: 1900
      targetPort: 1900
      protocol: UDP
      name: controller-l2-discovery
    - port: 5514
      targetPort: 5414
      protocol: UDP
      name: syslog
