apiVersion: v1
kind: Service
metadata:
  name: web-test
spec:
  selector:
    app: web-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-test
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
