# This is the values.yaml I used on my k3s raspberrypi cluster

# if you have a problem with serviceWeb Pods not building you might need to checkout this issue:
# https://github.com/MoJo2600/pihole-kubernetes/issues/230

ingress:
  enabled: true

serviceWeb:
  loadBalancerIP: 10.0.0.201
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 10.0.0.201
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDhcp:
  loadBalancerIP: 10.0.0.201
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 8.8.8.8

#! use an existing secret in a prod env
adminPassword: "pihole"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

