apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole  
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env: 
        - name: TZ
          value: "Europe/Madrid"
        - name: WEBPASSWORD
          value: "pihole"
