apiVersion: v1
kind: Pod
metadata:
  name: pihole
  namespace: pihole
spec:
  hostNetwork: {{ .Values.pihole.hostNetwork }}
  dnsPolicy: {{ .Values.pihole.dnsPolicy }}
  dnsConfig:
    nameservers:
      - {{ .Values.pihole.dnsConfig.nameservers | join " - " }}
  containers:
    - name: pihole
      image: {{ .Values.pihole.image }}
      imagePullPolicy: IfNotPresent
      env:
        - name: TZ
          value: {{ .Values.pihole.tz }}
        - name: WEBPASSWORD
          value: {{ .Values.pihole.webpassword }}
      securityContext:
        privileged: true
      ports:
        {{- range .Values.pihole.ports }}
        - containerPort: {{ .containerPort }}
          protocol: {{ .protocol }}
        {{- end }} 
      resources:
        requests:
          memory: {{ .Values.pihole.resources.requests.memory }}
          cpu: {{ .Values.pihole.resources.requests.cpu }}
        limits:
          memory: {{ .Values.pihole.resources.limits.memory }}
          cpu: {{ .Values.pihole.resources.limits.cpu }}
  volumes:
    - name: etc
      hostPath:
        path: /data/pihole/etc
        type: Directory
    - name: dnsmasq
      hostPath:
        path: /data/pihole/dnsmasq.d
        type: Directory
