apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 192.168.1.245
  ports:
  - name: admin-web
    port: 80
    targetPort: 80
    protocol: TCP
  - name: dns-tcp
    port: 53
    targetPort: 53  
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  - name: admin-web-https
    port: 443
    targetPort: 443
    protocol: TCP
      

