apiVersion: v1
kind: Service
metadata:
  name: pihole-admin-page
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 10.0.0.200
  ports:
  - name: admin-web
    port: 80
    targetPort: 80
    protocol: TCP
  - name: admin-web-https
    port: 443
    targetPort: 443
    protocol: TCP
