apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 10.0.0.201
  ports: 
  - name: dns-tcp
    port: 53
    targetPort: dns  
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 10.0.0.201
  ports: 
  - name: dns-udp
    port: 53
    targetPort: dns-udp
    protocol: UDP
