apiVersion: v1
kind: Service
metadata:
  name: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 192.168.1.245
  ports:
  - name: dns-tcp
    port: 53
    targetPort: 53  
    protocol: TCP
