apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ubiquiti-unifi-controller.fullname" . }}
  labels:
    {{- include "ubiquiti-unifi-controller.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ubiquiti-unifi-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ubiquiti-unifi-controller.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ubiquiti-unifi-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "{{ .Values.environment.PUID }}"
            - name: PGID
              value: "{{ .Values.environment.PGID }}"
            - name: TZ
              value: "{{ .Values.environment.TZ }}"
            - name: MEM_LIMIT
              value: "{{ .Values.environment.MEM_LIMIT }}"
            - name: MEM_STARTUP
              value: "{{ .Values.environment.MEM_STARTUP }}"
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          volumeMounts:
            - name: data-volume
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data-volume
          hostPath:
            path: {{ .Values.volumes.data }}
